settings:
  production: False
  debug: True
  app_name: 'Mi Flask APP'
  secret_key: 'TOKEN MUY SEGURO'
  template_folder: './app/templates'
  static_folder: './app/static'
db_connection:
  host: 'localhost'
  user: 'root'
  password: ''
  database: 'task_list_flask'

